### ISSUE TITLE
Date.date is not exported

### ISSUE THREAD

**Issue by ajcasagrande** [IOTechSystems/onvif#18]
https://github.com/IOTechSystems/onvif/blob/ffaba21822baab4050e17f70144e592e7e5a3880/xsd/built_in.go#L277-L281

This makes it harder to get the date (day) field of the Date from an external application

**Comment by ajcasagrande** [comment]
Also, I noticed that the field is called `Day` in the `PUT SystemDateAndTime` command.

**Comment by weichou1229** [comment]
> Also, I noticed that the field is called `Day` in the `PUT SystemDateAndTime` command.

Right, it is`Day` in the spec https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl#op.GetSystemDateAndTime
